### ISSUE TITLE
`useSearch` does not work in SSR

### ISSUE THREAD

**Issue by xxxhussein** [molefrog/wouter#345]
`ReferenceError: location is not defined` when doing SSR

```tsx
import { renderToString } from "react-dom/server";
import { Router } from "wouter";
import { App } from "./app";

console.log(
  renderToString(
    <Router ssrPath="/">
      <App />
    </Router>
  )
);
```

```tsx
// app.tsx

import { Link, Route } from "wouter";

export const App = () => (
  <>
    <Route
      path="/"
      component={() => (
        <div>
          <h1>Home</h1>
          <Link to="/about">About</Link>
        </div>
      )}
    />
    <Route
      path="/about"
      component={() => (
        <div>
          <h1>About</h1>
          <Link to="/">Home</Link>
        </div>
      )}
    />
  </>
);
```

**Comment by molefrog** [comment]
Hi @xxxhussein, thank you for reporting. What version of wouter and Node are you using?

**Comment by nitelite** [comment]
I am seeing a similar error message running Node 18.16.0 with `<Router srrPath={path}>...</Router>` wrapped around my normal routing code in my server-side entry point. I have verified that ssrPath gets set to "/" as a prop, but uncertain how to debug what happens inside the deeper parts of wouter.

Based on the stack trace it seems to be related to the Link component, and the useRouter() hook it uses. Maybe not being able to pick up the ssr-enabled Router from context? 

Through `useSyncExternalStore()` it ends up eventually calling `useSearch()` which seems to only have one implementation, and thats `useLocationProperty()` with a function that fetches from `location.search`. Since location does not exist, it crashes attempting to read `search`.

**Comment by molefrog** [comment]
Hi @nitelite, indeed `useSearch` currently does not support SSR 😢 
We have addressed this in the new version https://github.com/molefrog/wouter/pull/373, which is almost ready for the first release. Unfortunately, I had to freeze the development on v2, so please stay tuned 🙏

**Comment by nitelite** [comment]
It seems like the <Link> component (which I use all over the app to create links to other parts of the app) uses `useLocationFromRouter()` which, even thought its not using location from the hook, might result in attempting to subscribe to changes to the location property. These `useSyncExternalStore()` called attempt to uses "currentSearch" and "currentPathname" functions as "external stores".

I was able to temporarily work-around the error messages by modifying these functions in use-location.js, adding some guard rails, but I don't know if this has any other unwanted side effects:

```
const currentSearch = () => typeof location !== "undefined" ? location.search : "";
const currentPathname = () => typeof location !== "undefined" ? location.pathname : "";
```

**Comment by molefrog** [comment]
The RC is [finally out](https://github.com/molefrog/wouter/releases/tag/v3.0.0-rc.1). Here is how you can use it in SSR now (I borrowed this example from one of my apps):

```
import { useSearch } from "wouter"

function ServerApp({ context }: { context: Context }) {
  const requestUrl = new URL(context.req.url);

  return ( 
    /* e.g. path is "/" and ssrSearch is "foo=bar&baz" */
    <Router ssrPath={requestUrl.pathname} ssrSearch={requestUrl.search}>
      <App />
    </Router>
  );
}
```

**Comment by TomMarius** [comment]
Hello, I am still having this issue with wouter-preact 3.0.0-rc2. I have ssrPath and ssrSearch defined on my Router as per the example in the previous reply.

**Comment by TomMarius** [comment]
Hello, I am still having this issue with wouter-preact 3.0.0-rc2. I have the same code as in the previous reply.

Stacktrace:
```
ReferenceError: location is not defined
    at currentPathname (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/use-browser-location.js:38:40)
    at useSyncExternalStore (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/preact-deps-dec5c677.js:18:17)
    at useLocationProperty (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/use-browser-location.js:31:3)
    at usePathname (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/use-browser-location.js:41:3)
    at Object.useBrowserLocation [as hook] (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/use-browser-location.js:55:44)
    at useLocationFromRouter (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/index.js:75:39)
    at Object.Switch (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/wouter-preact@3.0.0-rc.2_preact@10.19.3/node_modules/wouter-preact/esm/index.js:254:30)
    at C (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/preact-render-to-string@6.3.1_preact@10.19.3/node_modules/preact-render-to-string/dist/index.mjs:1:3242)
    at C (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/preact-render-to-string@6.3.1_preact@10.19.3/node_modules/preact-render-to-string/dist/index.mjs:1:3807)
    at C (file:///Users/tom/Documents/MSWProjects/preact-test/node_modules/.pnpm/preact-render-to-string@6.3.1_preact@10.19.3/node_modules/preact-render-to-string/dist/index.mjs:1:2542)
```
